entity:
  AREA_EFFECT_CLOUD:
  ARMOR_STAND: 盔甲架
  ARROW: 箭
  BAT: 蝙蝠
  BLAZE: 烈焰怪
  BOAT: Nice Boat
  CAVE_SPIDER: 洞穴蜘蛛
  CHICKEN: 小鸡鸡
  COMPLEX_PART:
  COW: 老母牛
  CREEPER: JJ怪
  DONKEY: 驴
  DRAGON_FIREBALL: 龙的火球
  DROPPED_ITEM: 掉落物品
  EGG: 蛋蛋
  ELDER_GUARDIAN: 远古守卫者
  ENDER_CRYSTAL: 末影水晶
  ENDER_DRAGON: 末影龙
  ENDER_PEARL: 末影珍珠
  ENDER_SIGNAL:
  ENDERMAN: 黑基佬
  ENDERMITE: 末影螨
  EVOKER:
  EVOKER_FANGS:
  EXPERIENCE_ORB: 经验球
  FALLING_BLOCK: 坠落的方块
  FIREBALL: 火球
  FIREWORK: 烟花
  FISHING_HOOK: 鱼钩
  GHAST: 恶魂
  GIANT: 巨人
  GUARDIAN: 守护者
  HORSE: 马
  HUSK: 尸壳
  ILLUSIONER:
  IRON_GOLEM: 铁傀儡
  ITEM_FRAME: 物品展示框
  LEASH_HITCH:
  LIGHTNING: 闪电
  LINGERING_POTION: 滞留药水
  LLAMA: 羊驼
  LLAMA_SPIT: 羊驼：喷射唾沫
  MAGMA_CUBE: 岩浆怪
  MINECART: 矿车
  MINECART_CHEST: 箱子矿车
  MINECART_COMMAND: 命令矿车
  MINECART_FURNACE: 动力矿车
  MINECART_HOPPER: 漏斗矿车
  MINECART_MOB_SPAWNER: 刷怪矿车
  MINECART_TNT: TNT矿车
  MULE: 骡
  MUSHROOM_COW: 哞菇
  OCELOT: 豹猫
  PAINTING: 画
  PARROT: 鹦鹉
  PIG: 猪
  PIG_ZOMBIE: 僵尸猪人
  PLAYER: 玩家
  POLAR_BEAR: 鹦鹉：低吼
  PRIMED_TNT: 点燃的TNT
  RABBIT: 兔子
  SHEEP: 羊
  SHULKER: 潜影贝
  SHULKER_BULLET: 潜影贝导弹
  SILVERFISH: 蠢虫
  SKELETON: 骷髅弓箭手
  SKELETON_HORSE: 骷髅马
  SLIME: 史莱姆
  SMALL_FIREBALL: 小火球
  SNOWBALL: 雪球
  SNOWMAN: 雪人
  SPECTRAL_ARROW: 光灵箭
  SPIDER: 蜘蛛
  SPLASH_POTION: 喷溅药水
  SQUID: 乌贼
  STRAY: 流髑
  THROWN_EXP_BOTTLE:
  TIPPED_ARROW: 药箭
  UNKNOWN: 未知物体
  VEX: 恼鬼
  VILLAGER: 村民
  VINDICATOR:
  WEATHER: 天气
  WITCH: 女巫
  WITHER: 凋灵
  WITHER_SKELETON: 凋灵骷髅
  WITHER_SKULL: 凋灵骷髅的头颅
  WOLF: 狼
  ZOMBIE: 僵尸
  ZOMBIE_HORSE: 僵尸马
  ZOMBIE_VILLAGER: 僵尸村民
reason:
  CLOSEST_ENTITY: 离太近了
  CLOSEST_PLAYER: 你离它太近了
  COLLISION: 你撞了它
  CUSTOM: 某些原因
  DEFEND_VILLAGE: 保卫村庄
  FORGOT_TARGET: 它放弃了原有目标
  OWNER_ATTACKED_TARGET: 它的主人正在攻击你
  PIG_ZOMBIE_TARGET: 你犯了众怒
  RANDOM_TARGET: 你长得丑
  REINFORCEMENT_TARGET: 它叫来了援兵
  TARGET_ATTACKED_ENTITY: 你打了它
  TARGET_ATTACKED_NEARBY_ENTITY: 你打了它
  TARGET_ATTACKED_OWNER: 你打了它主人
  TARGET_DIED: OT了
  TEMPT: 被引诱了
  UNKNOWN: No why
