entity:
    ARROW: 弓箭
    BAT: 蝙蝠  
    BLAZE: 烈焰人
    BOAT: 船
    CAVE_SPIDER: 洞穴蜘蛛
    CHICKEN: 小鸡鸡
    COMPLEX_PART: 奇怪的东西
    COW: 牛
    CREEPER: JJ怪
    DROPPED_ITEM: 掉落物品
    EGG: 蛋蛋
    ENDER_CRYSTAL: 末影水晶
    ENDER_DRAGON: 末影龙
    ENDER_PEARL: 末影珍珠
    ENDER_SIGNAL: 奇怪的东西
    ENDERMAN: 黑基佬
    EXPERIENCE_ORB: 经验球
    FALLING_BLOCK: 掉落的方块
    FIREBALL: 火球
    FIREWORK: 烟花
    FISHING_HOOK: 鱼钩
    GHAST: 恶魂
    GIANT: 巨人僵尸
    HORSE: 马
    IRON_GOLEM: 铁傀儡
    ITEM_FRAME: 奇怪的东西
    LEASH_HITCH: 奇怪的东西
    LIGHTNING: 奇怪的东西
    MAGMA_CUBE: 岩浆怪
    MINECART: 矿车
    MINECART_CHEST: 箱子矿车
    MINECART_FURNACE: 炉子矿车
    MINECART_HOPPER: 漏斗矿车
    MINECART_MOB_SPAWNER: 奇怪的东西
    MINECART_TNT: TNT矿车
    MUSHROOM_COW: 咩菇
    OCELOT: 豹猫
    PAINTING: 画
    PIG: 猪
    PIG_ZOMBIE: 僵尸猪人
    PLAYER: 玩家
    PRIMED_TNT: 点燃的TNT
    SHEEP: 羊
    SILVERFISH: 蠹虫
    SKELETON: 骷髅弓箭手
    SLIME: 小软
    SMALL_FIREBALL: 小火球
    SNOWBALL: 雪球
    SNOWMAN: 雪人
    SPIDER: 蜘蛛
    SPLASH_POTION: 奇怪的东西
    SQUID: 鱿鱼
    THROWN_EXP_BOTTLE: 掉落的经验瓶
    UNKNOWN: 不知名的东西
    VILLAGER: 村民
    WEATHER: 天气
    WITCH: 女巫
    WITHER: 凋灵
    WITHER_SKULL: 凋灵头骨
    WOLF: 狼
    ZOMBIE: 僵尸